server:
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/juancarllos88/alura-config.git
          #uri: https://github.com/rafaelcam/delivery-configs.git
          #skip-ssl-validation: true
          uri: https://github.com/juancarllos88/alura-config
          search-paths:
          - forum
          - loja
          - fornecedor
          - transportador
#  profiles:
#    active:
#    - native
  application:
    name: config-server
    
    
#eureka        
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true    
    
    